---
# Teardown K8s cluster using kops
- debug:
     msg: "----THE VALUE OF THE VARIABLE IS "

- import_tasks: teardown-cloud-resource.yaml

- name: Export Kops state store
  shell: export KOPS_STATE_STORE=s3://{{bucket_name}}

- name:
  command: kops delete cluster --name {{cluster_name}} --yes --state=s3://{{bucket_name}}




# - name: Empty S3 bucket 
#   shell: aws s3 rm s3://{{bucket_name}} --recursive

# - name: Delete S3 bucket
#   command: aws s3api delete-objects --bucket {{bucket_name}} --delete "$(aws s3api list-object-versions --bucket {{bucket_name}} --output=json --query='{Objects.Versions[].{Key:Key,VersionId:VersionId}}')"

# - name:
#   command: 
