---
- debug:
    msg: "the vasdfsd -- {{group_name}}"

- name: Attach policy
  command: aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess --group-name {{group_name}} 

- name: Create ECR repository
  command: aws ecr create-repository --repository-name csye7374

- name: Working Directory
  register: pwd
  command: echo $PWD

- debug:
    var: pwd 

- name: Build docker
  command: docker build --no-cache -t csye7374 ../webapp/.

- name: Tag Docker image
  command: docker tag csye7374:latest {{account_num}}.dkr.ecr.us-east-1.amazonaws.com/csye7374:latest

# - name: configmap
#   shell: kubectl create configmap aws-config-map --from-literal=amazonProperties.endpointUrl="https://s3.us-east-1.amazonaws.com" --from-literal=amazonProperties.bucketName={{bucket_name}}

# - name: SecretMap
#   shell: kubectl create secret generic aws-db-secret --from-literal=username=username --from-literal=password=password --from-literal=dburl=jdbc:mysql://csye7374.cxqpnnn7mmz9.us-east-1.rds.amazonaws.com:3306/dbname101?useSSL=false --from-literal=accessKey={{accessKey}} --from-literal=secretKey={{secretKey}}
